// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:bismillah/main.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqXeyoyRZdz_QIpKlx6EN6xnh2kXh5gn4',
    appId: '1:519067039620:web:077eb2066017d755510fd1',
    messagingSenderId: '519067039620',
    projectId: 'projectify-f272a',
    authDomain: 'projectify-f272a.firebaseapp.com',
    storageBucket: 'projectify-f272a.firebasestorage.app',
    measurementId: 'G-QLCJMESZCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5sL-3zlzWx31Pr-TUGSqp9ggH4fDSi2k',
    appId: '1:519067039620:android:73830ffcd5fa0047510fd1',
    messagingSenderId: '519067039620',
    projectId: 'projectify-f272a',
    storageBucket: 'projectify-f272a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeR9DPW8_eYVoszF70hl9NIOjgaBf8Z4c',
    appId: '1:519067039620:ios:6710a64d10e89b8c510fd1',
    messagingSenderId: '519067039620',
    projectId: 'projectify-f272a',
    storageBucket: 'projectify-f272a.firebasestorage.app',
    iosBundleId: 'com.example.bismillah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeR9DPW8_eYVoszF70hl9NIOjgaBf8Z4c',
    appId: '1:519067039620:ios:6710a64d10e89b8c510fd1',
    messagingSenderId: '519067039620',
    projectId: 'projectify-f272a',
    storageBucket: 'projectify-f272a.firebasestorage.app',
    iosBundleId: 'com.example.bismillah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqXeyoyRZdz_QIpKlx6EN6xnh2kXh5gn4',
    appId: '1:519067039620:web:f4dbdf85374f0351510fd1',
    messagingSenderId: '519067039620',
    projectId: 'projectify-f272a',
    authDomain: 'projectify-f272a.firebaseapp.com',
    storageBucket: 'projectify-f272a.firebasestorage.app',
    measurementId: 'G-5THC9Z5BPD',
  );
}
